
[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/buffalo"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/envy"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/packr"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/suite"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/goth"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/grift"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/pop"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/validate"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/satori/go.uuid"
